"""FEN-SYNC snapshot generator (versioned copy - see also the machine-local canonical at C:\FEN-GRAPHIA\) - single local source of truth for working chats.

Recreated 2026-09-02 after the D: (SD card) failure destroyed the previous
copy. Canonical location: C:\FEN-GRAPHIA\fen_sync_check.py, writes
C:\FEN-GRAPHIA\FEN-SYNC.md. Repo home: C:\fen-triadic-synthesis.
Usage: python C:\FEN-GRAPHIA\fen_sync_check.py (git/gh on PATH; deps in C:\fen-venv)
"""
import datetime
import os
import re
import subprocess

REPO = r"C:\fen-triadic-synthesis"
OUT = r"C:\FEN-GRAPHIA\FEN-SYNC.md"
VENV_PY = r"C:\fen-venv\Scripts\python.exe"
KEY_FILES = [
    "README.md", "CHANGELOG.md", "docs/BACKLOG.md", "docs/self-hosted-runner.md",
    "docs/ontology/fen-ontology.ttl", "docker-compose.yml", "web/portal/index.html",
    "web/widget/fen-status-widget.js", "mock_fen_api/main.py",
    "services/status_api/main.py", "services/fen_bridge/webhook.py",
    "services/validation_consumer/sparql_updater.py", "services/common/kafka_io.py",
    "docs/FEN-Whitepaper-Triadic-Synthesis.pdf", "web/api.md", "vercel.json",
    "tests/test_status_api.py", "scripts/smoke_test.py",
    ".github/workflows/ci.yml", ".github/workflows/web.yml",
]


def run(args, cwd=REPO, timeout=300):
    try:
        p = subprocess.run(args, cwd=cwd, capture_output=True, text=True, timeout=timeout)
        return (p.stdout or "").strip()
    except Exception:
        return ""


def main():
    head = run(["git", "log", "-1", "--format=%h"])
    count = run(["git", "rev-list", "--count", "HEAD"])
    branch = run(["git", "branch", "--show-current"])
    dirty = [l for l in run(["git", "status", "-s"]).splitlines() if l.strip()]
    tree = "CLEAN" if not dirty else "DIRTY (%d files)" % len(dirty)
    unpushed = len([l for l in run(["git", "log", "origin/main..HEAD", "--oneline"]).splitlines() if l.strip()])
    tests = run([VENV_PY, "-m", "pytest", "-q"])
    passed = "?"
    for line in reversed(tests.splitlines()):
        m = re.search(r"(\d+) passed", line)
        if m:
            passed = m.group(1)
            break
    ci = run(["gh", "-R", "riznykst/fen-triadic-synthesis", "run", "list", "--limit", "1",
              "--json", "databaseId,status,conclusion,displayTitle,startedAt,createdAt",
              "--jq", ".[0] | [.databaseId, .status, .conclusion, .displayTitle, .duration, .createdAt] | @tsv"])
    last5 = run(["git", "log", "--oneline", "-5"]).splitlines()
    missing = [f for f in KEY_FILES if not os.path.exists(os.path.join(REPO, *f.split("/")))]
    artifact = ("OK: %d/%d key files present" % (len(KEY_FILES) - len(missing), len(KEY_FILES))
                if not missing else "MISSING: " + ", ".join(missing))
    backlog = []
    bp = os.path.join(REPO, "docs", "BACKLOG.md")
    if os.path.exists(bp):
        with open(bp, encoding="utf-8") as fh:
            backlog = [l.rstrip() for l in fh if l.startswith("- [ ]")]
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    md = """# FEN - SYNC (single local source of truth for working chats)

_Generated by `fen_sync_check.py` - {now}. Refresh after every change._

## Snapshot

- Repo: `{repo}` (branch `{branch}`)
- HEAD: `{head}` - {count} commits on main
- Working tree: {tree}
- Tests: {passed} passed (pytest, C:\\fen-venv)
- CI (latest): {ci}
- Unpushed commits: {unpushed}

## Working rules (all chats)

1. Roadmap-only: no feature outside docs/BACKLOG.md that contradicts the
   whitepaper or ADR-001..006; ADR conflicts are discussed, not coded around.
2. Frontend changes (web/) land in SEPARATE commits from backend changes.
3. Honesty contract: README/CHANGELOG/BACKLOG/FEN-SYNC must match the repo
   (test counts, CI status, mock vs real). Never claim verified what is not.
4. Push only from a clean tree; check `git status -s` first (parallel
   sessions commit into this repo).
5. CI runs on a self-hosted runner (push-only, C:\\actions-runner);
   COMPOSE_PROJECT_NAME=fen-ci isolates it from the local dev stack.
   Docker must be running for e2e.
6. After any change: pytest (C:\\fen-venv), update CHANGELOG/BACKLOG/README
   counts, then `python C:\\FEN-GRAPHIA\\fen_sync_check.py` to refresh this file.

## Last 5 commits

```
{last5}
```

## Artefact check

- {artifact}

## Open backlog items (docs/BACKLOG.md)

{backlog}
""".format(now=now, repo=REPO, branch=branch, head=head, count=count, tree=tree,
           passed=passed, ci=ci, unpushed=unpushed, last5="\n".join(last5),
           artifact=artifact, backlog="\n".join(backlog) if backlog else "(none)")
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(md)
    print("-> refreshed", OUT)


if __name__ == "__main__":
    main()
